
ALTER TABLE public.trips
  ADD COLUMN IF NOT EXISTS meal_plan TEXT,
  ADD COLUMN IF NOT EXISTS room_type TEXT,
  ADD COLUMN IF NOT EXISTS airline TEXT,
  ADD COLUMN IF NOT EXISTS flight_number TEXT,
  ADD COLUMN IF NOT EXISTS locator_code TEXT,
  ADD COLUMN IF NOT EXISTS num_nights INTEGER,
  ADD COLUMN IF NOT EXISTS pax_count INTEGER,
  ADD COLUMN IF NOT EXISTS total_value NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS insurance_company TEXT,
  ADD COLUMN IF NOT EXISTS insurance_policy TEXT,
  ADD COLUMN IF NOT EXISTS itinerary_id UUID REFERENCES public.itineraries(id) ON DELETE SET NULL;
